name: Test Composite Action

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Karen"
      # - name: ls
      #   run: |
      #     chmod +x script.sh
      #     ./script.sh
